# Blackterio's Glide Extra Functions
glide.input.door_animations=Blackterio Özel Animasyonları - Kontroller
glide.input.animation_1=Animasyon 1
glide.input.animation_2=Animasyon 2
glide.input.animation_3=Animasyon 3
glide.input.animation_4=Animasyon 4
glide.input.animation_5=Animasyon 5
glide.input.animation_6=Animasyon 6
glide.input.animation_7=Animasyon 7
glide.input.animation_8=Animasyon 8
glide.input.animation_9=Animasyon 9
glide.input.animation_all=Tüm animasyonlar
glide.input.toggle_wipers=Silecekleri aç/kapat
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=Manuel silecekler (tuşla aç/kapat)
blackterio.config.wipers_sound=Silecek seslerini etkinleştir
blackterio.config.aimdoors_enable=Nişan alarak kapı aç ([E] kapılar, kaput, bagaj)
blackterio.config.aimdoors_hint=Kapı ipuçlarını göster ([E] Aç/Kapat)
blackterio.aim.open=[%s] Aç
blackterio.aim.enter=[%s] Bin
blackterio.aim.close_shift=[%s + %s] Kapat
blackterio.aim.close=[%s] Kapat
blackterio.aim.friend_locked=(Kilitli - arkadaşlar)
blackterio.aim.locked=(Kilitli)
