# Blackterio's Glide Extra Functions
glide.input.door_animations=Blackterio 自定义动画 - 控制
glide.input.animation_1=动画 1
glide.input.animation_2=动画 2
glide.input.animation_3=动画 3
glide.input.animation_4=动画 4
glide.input.animation_5=动画 5
glide.input.animation_6=动画 6
glide.input.animation_7=动画 7
glide.input.animation_8=动画 8
glide.input.animation_9=动画 9
glide.input.animation_all=全部动画
glide.input.toggle_wipers=切换雨刮器
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=手动雨刮器 (按键切换)
blackterio.config.wipers_sound=启用雨刮器音效
blackterio.config.aimdoors_enable=瞄准开门 (对车门、引擎盖、后备箱按 [E])
blackterio.config.aimdoors_hint=显示车门提示 ([E] 打开/关闭)
blackterio.aim.open=[%s] 打开
blackterio.aim.enter=[%s] 上车
blackterio.aim.close_shift=[%s + %s] 关闭
blackterio.aim.close=[%s] 关闭
blackterio.aim.friend_locked=(好友可进)
blackterio.aim.locked=(已上锁)
