# Blackterio's Glide Extra Functions
glide.input.door_animations=Користувацькі анімації Blackterio - Керування
glide.input.animation_1=Анімація 1
glide.input.animation_2=Анімація 2
glide.input.animation_3=Анімація 3
glide.input.animation_4=Анімація 4
glide.input.animation_5=Анімація 5
glide.input.animation_6=Анімація 6
glide.input.animation_7=Анімація 7
glide.input.animation_8=Анімація 8
glide.input.animation_9=Анімація 9
glide.input.animation_all=Усі анімації
glide.input.toggle_wipers=Увімк/вимк двірники
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=Ручні двірники (увімкнення клавішею)
blackterio.config.wipers_sound=Увімкнути звуки двірників
blackterio.config.aimdoors_enable=Відчиняти двері прицілом ([E] на дверях, капоті, багажнику)
blackterio.config.aimdoors_hint=Показувати підказки дверей ([E] Відчинити/Зачинити)
blackterio.aim.open=[%s] Відчинити
blackterio.aim.enter=[%s] Сісти
blackterio.aim.close_shift=[%s + %s] Зачинити
blackterio.aim.close=[%s] Зачинити
blackterio.aim.friend_locked=(Замкнено - друзі)
blackterio.aim.locked=(Замкнено)
