# Blackterio's Glide Extra Functions
glide.input.door_animations=Animaciones personalizadas de Blackterio - Controles
glide.input.animation_1=Animación 1
glide.input.animation_2=Animación 2
glide.input.animation_3=Animación 3
glide.input.animation_4=Animación 4
glide.input.animation_5=Animación 5
glide.input.animation_6=Animación 6
glide.input.animation_7=Animación 7
glide.input.animation_8=Animación 8
glide.input.animation_9=Animación 9
glide.input.animation_all=Todas las animaciones
glide.input.toggle_wipers=Activar/desactivar limpiaparabrisas
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=Limpiaparabrisas manuales (activar con tecla)
blackterio.config.wipers_sound=Activar sonidos del limpiaparabrisas
blackterio.config.aimdoors_enable=Abrir puertas apuntando ([E] en puertas, capó y baúl)
blackterio.config.aimdoors_hint=Mostrar ayudas de puertas ([E] Abrir/Cerrar)
blackterio.aim.open=[%s] Abrir
blackterio.aim.enter=[%s] Subir
blackterio.aim.close_shift=[%s + %s] Cerrar
blackterio.aim.close=[%s] Cerrar
blackterio.aim.friend_locked=(Solo amigos)
blackterio.aim.locked=(Bloqueado)
