# Blackterio's Glide Extra Functions
glide.input.door_animations=Пользовательские анимации Blackterio - Управление
glide.input.animation_1=Анимация 1
glide.input.animation_2=Анимация 2
glide.input.animation_3=Анимация 3
glide.input.animation_4=Анимация 4
glide.input.animation_5=Анимация 5
glide.input.animation_6=Анимация 6
glide.input.animation_7=Анимация 7
glide.input.animation_8=Анимация 8
glide.input.animation_9=Анимация 9
glide.input.animation_all=Все анимации
glide.input.toggle_wipers=Вкл/выкл дворники
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=Ручные дворники (включение клавишей)
blackterio.config.wipers_sound=Включить звуки дворников
blackterio.config.aimdoors_enable=Открывать двери прицелом ([E] на дверях, капоте, багажнике)
blackterio.config.aimdoors_hint=Показывать подсказки дверей ([E] Открыть/Закрыть)
blackterio.aim.open=[%s] Открыть
blackterio.aim.enter=[%s] Сесть
blackterio.aim.close_shift=[%s + %s] Закрыть
blackterio.aim.close=[%s] Закрыть
blackterio.aim.friend_locked=(Заперто - друзья)
blackterio.aim.locked=(Заперто)
