# Blackterio's Glide Extra Functions
glide.input.door_animations=Animações personalizadas do Blackterio - Controles
glide.input.animation_1=Animação 1
glide.input.animation_2=Animação 2
glide.input.animation_3=Animação 3
glide.input.animation_4=Animação 4
glide.input.animation_5=Animação 5
glide.input.animation_6=Animação 6
glide.input.animation_7=Animação 7
glide.input.animation_8=Animação 8
glide.input.animation_9=Animação 9
glide.input.animation_all=Todas as animações
glide.input.toggle_wipers=Ligar/desligar limpadores
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=Limpadores manuais (ativar com tecla)
blackterio.config.wipers_sound=Ativar sons dos limpadores
blackterio.config.aimdoors_enable=Abrir portas mirando ([E] em portas, capô e porta-malas)
blackterio.config.aimdoors_hint=Mostrar dicas das portas ([E] Abrir/Fechar)
blackterio.aim.open=[%s] Abrir
blackterio.aim.enter=[%s] Entrar
blackterio.aim.close_shift=[%s + %s] Fechar
blackterio.aim.close=[%s] Fechar
blackterio.aim.friend_locked=(Trancado - amigos)
blackterio.aim.locked=(Trancado)
