# Blackterio's Glide Extra Functions
glide.input.door_animations=Animations personnalisées de Blackterio - Commandes
glide.input.animation_1=Animation 1
glide.input.animation_2=Animation 2
glide.input.animation_3=Animation 3
glide.input.animation_4=Animation 4
glide.input.animation_5=Animation 5
glide.input.animation_6=Animation 6
glide.input.animation_7=Animation 7
glide.input.animation_8=Animation 8
glide.input.animation_9=Animation 9
glide.input.animation_all=Toutes les animations
glide.input.toggle_wipers=Activer/désactiver les essuie-glaces
blackterio.config.header=Extra Functions
blackterio.config.wipers_manual=Essuie-glaces manuels (activation par touche)
blackterio.config.wipers_sound=Activer les sons des essuie-glaces
blackterio.config.aimdoors_enable=Ouvrir les portes en visant ([E] sur portes, capot, coffre)
blackterio.config.aimdoors_hint=Afficher les aides des portes ([E] Ouvrir/Fermer)
blackterio.aim.open=[%s] Ouvrir
blackterio.aim.enter=[%s] Monter
blackterio.aim.close_shift=[%s + %s] Fermer
blackterio.aim.close=[%s] Fermer
blackterio.aim.friend_locked=(Verrouillé - amis)
blackterio.aim.locked=(Verrouillé)
